development:
  redis:
    host: localhost
    port: 6379
    expires_in: <%= 1.hour %>

test:
  redis:
    host: localhost
    port: 6379
    expires_in: <%= 1.hour %>

production:
  redis:
    host: <%= ENV["REDIS_HOST"] %>
    port: <%= ENV["REDIS_PORT"] %>
    db: <%= ENV["REDIS_DB"] %>
    expires_in: <%= 1.hour %>
