development:
  redis:
    host: <%= ENV['REDIS_HOST'] || "localhost" %>
    port: 6379
    db: demoredis-001
    expires_in: <%= 1.hour %>

test:
  redis:
    host: <%= ENV['REDIS_HOST'] || "localhost" %>
    port: 6379
    db: demoredis-001
    expires_in: <%= 1.hour %>

production:
  redis:
    host: <%= ENV['REDIS_HOST'] || "localhost" %>
    port: 6379
    db: demoredis-001
    expires_in: <%= 1.hour %>
